TTLocalizer: Running in language: english
from toontown.toonbase.TTLocalizerEnglish import *
OTPLocalizer: Running in language: english
from otp.otpbase.OTPLocalizerEnglish import *
Preloading suits...
Preloading Toon heads...
Preloading avatars...
Traceback (most recent call last):
  File "<string>", line 3, in <module>
NameError: name 'self' is not defined

{401000001: <toontown.distributed.ToontownDistrict.ToontownDistrict instance at 0x1F535238>}
Traceback (most recent call last):
  File "D:\Documents\ToontownSourcecode\Toontown\toontown\toonbase\ClientStart.py", line 246, in tick
    self.root.update()
  File "D:\Documents\ToontownSourcecode\Panda3D-1.9.0\python\lib\lib-tk\Tkinter.py", line 962, in update
    self.tk.call('update')
_tkinter.TclError: can't invoke "update" command:  application has been destroyed
Traceback (most recent call last):
  File "otp\otpbase\OTPBase.py", line 236, in run
    taskMgr.run()
  File "D:\Documents\ToontownSourcecode\Panda3D-1.9.0\direct\task\Task.py", line 502, in run
    self.step()
  File "D:\Documents\ToontownSourcecode\Panda3D-1.9.0\direct\task\Task.py", line 460, in step
    self.mgr.poll()
  File "D:\Documents\ToontownSourcecode\Toontown\toontown\toonbase\ClientStart.py", line 246, in tick
    self.root.update()
  File "D:\Documents\ToontownSourcecode\Panda3D-1.9.0\python\lib\lib-tk\Tkinter.py", line 962, in update
    self.tk.call('update')
TclError: can't invoke "update" command:  application has been destroyed
